### ISSUE TITLE
Error starting the linux binary executable

### ISSUE THREAD

**Issue by royfrancis** [MWSchmid/Rcount#3]
``` bash
$ ./Rcount-distribute
./Rcount-distribute: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
```

**Comment by MWSchmid** [comment]
thanks for the report. Looks like it does not search the current directory for the libraries...

You can "fix it" if you install the Qt5 libraries:

```
sudo apt-get install qt5-default
```

**Comment by MWSchmid** [comment]
I checked it briefly - installing the Qt5 libraries system wide is the most simple and stable approach. I modified the user guide and removed the shared libraries from the linux archive. Thanks for your report.
